# Generated by Django 4.0.4 on 2022-05-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
